
# File generated by: /usr/local/bin/mkver.pl -e mak env epm
# Do not version or edit. Change by editing: ./ver.sh

ProdName=libre-bib
ProdAlias=libre-bib
ProdVer=1.2.6
ProdRC=
ProdBuild=1
ProdBuildTime=2026.08.14.18.10
ProdSvnVer=
ProdWinVer=1.2.6
ProdDate=2026-08-14
ProdSummary=Bibliography tool for LibreOffice
ProdDesc=Bibliography tool for LibreOffice
ProdSupport=turtle.engr.com
ProdVendor=TurtleEngr / turtle.engr.com
ProdPackager=TurtleEngr
ProdCopyright=Copyright 2026. All rights reserved.
ProdLicense=../LICENSE
ProdReadMe=../src/doc/manual/libre-bib.html
ProdTPVendor=
ProdTPVer=
ProdTPCopyright=
MkVer=2.2
ProdDesc=Bibliography tool for LibreOffice
ProdRelServer=moria.whyayh.com
ProdRelRoot=moria.whyayh.com:/rel
ProdRelCategory=software/own/libre-bib
ProdRelDir=moria.whyayh.com:/rel/released/software/own/libre-bib
ProdDevDir=moria.whyayh.com:/rel/development/software/own/libre-bib
ProdTag=tag-1-2-6-1
ProdOS=mx23
ProdOSDist=mx
ProdOSVer=23.6
ProdArch=x86_64

